
# A embedded H2 database is enabled in dev mode for development.
# while dev profile is enabled, the mysql isn't required anymore. The developer can maintain the data
# via this web console: http://ip:8080/h2
spring:
  datasource:
#      url: "jdbc:h2:file:~/h2/web_db;DB_CLOSE_ON_EXIT=FALSE"
      url: "jdbc:h2:mem:web;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE"
      username: root
      password: NextGen
      driver-class-name:  org.h2.Driver
      platform: h2
      data: classpath:/database/data-h2.sql
#      schema: classpath:/database/schema-h2.sql
      initialize: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create-drop  # Initialize the database and discard the data after
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true